server:
  port: 8080

spring:
  application:
    name: eureka-server1

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8080/eureka

