server:
  port: 8085


#  spring.security.user.name=admin
#  spring.security.user.password=admin
#
#  spring.application.name=spring-boot-admin
#  eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#  spring.boot.admin.discovery.ignored-services=spring-boot-admin
#

spring:
#  boot:
#    admin:
#      url: http://localhost:8090
  cloud:
    config:
      enabled: false
  application:
    name: admin-client5

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    fetchRegistry: true



